config/routes.rb
NewAnifag::Application.routes.draw do

  root :to => 'static_pages#home'

  devise_for :users, :controllers => { :invitations => 'users/invitations',
                                       :registrations => 'users/registrations' }
  
  devise_scope :user do
    get "signin", :to => "devise/sessions#new"
    match "signout", to: "devise/sessions#destroy", via: :delete
  end

  mount RedactorRails::Engine => '/redactor_rails'

  resources :users, only: [:show, :index]
  
  resources :articles  
  
  resources :categories
  resources :tags, only: [:index, :show]
  
  resources :forums
  resources :topics
  resources :topic_posts, except: [:show, :new]
  
  match '/search', to: 'static_pages#search'
  
  match '/users/:id/ban',  to: 'users#ban', as: :user_ban
  
  get '/archive(/:year(/:month))', to: 'archives#show', as: :archive
  
  get '/:year/:month/:id', to: 'articles#redirect_to_new'

end

app/models/forum.rb
# == Schema Information
#
# Table name: forums
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string(255)
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  protect    :boolean          default(FALSE)
#

class Forum < ActiveRecord::Base
  attr_accessible :content, :title, :protect
  
  belongs_to :user
  
  has_many :topics, dependent: :destroy
  
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 90 }
  
  default_scope order: 'forums.id ASC'
end

app/controllers/forums_controller.rb
# coding: utf-8
class ForumsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user, except: [:index ,:show]
  
  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
    @topics = @forum.topics.paginate(page: params[:page], :per_page => 30) 
  end
  
  def new    
    @forum = Forum.new  
  end
  
  def create
    @forum = current_user.forums.build(params[:forum])
    
    if @forum.save
      flash[:success] = "Форум создан."
      redirect_to @forum
    else
      render 'new'
    end
  end
  
  def edit
    @forum = Forum.find(params[:id])    
  end
  
  def update
    @forum = Forum.find(params[:id])    
    if @forum.update_attributes(params[:forum])
      flash[:success] = "Форум обновлен."
      redirect_to @forum
    else
      render 'edit'
    end    
  end
  
  def destroy
    @forum.destroy
    flash[:success] = "Форум удален."
    redirect_to forums_url    
  end
  
  private
    def correct_user
      redirect_to forums_path unless current_user.admin?
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_forum_form.html.erb
<section>
  <% if controller.action_name == 'new' %> 
    <h1>Новый форум</h1>
  <% else %>
    <h1>Редактирование форума</h1>
  <% end %>
  
  <div class="row">
    <div class="span6 offset3">
      <%= form_for(@forum) do |f| %>
        <% if @forum.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-error">
              Форма содержит <%= (@forum.errors.count).to_s + 
                                  " " + Russian::pluralize((@forum.errors.count), 
                                  "ошибку", "ошибки", "ошибок") %>.
            </div>
            <ul>
            <% @forum.errors.full_messages.each do |msg| %>
              <li>* <%= msg %></li>
            <% end %>>
            </ul>
          </div>
        <% end %>
  
        <%= f.label :title, "Название" %>
        <%= f.text_field :title %>
  
        <%= f.label :content, "Описание" %>
        <%= f.text_area :content %>
        
        <%= f.label :protect, class: "checkbox" do %>
          <%= f.check_box :protect  %> Запретить создание топиков
        <% end %>
  
        <% if controller.action_name == 'new' %>
            <%= f.submit "Создать", class: "btn btn-large btn-primary" %>
          <% else %>
            <% if @forum && @forum.id  %>
              <%= link_to "Удалить", @forum, method: :delete,
                                           data: { confirm: "Уверены?" },
                                           title: "Удалить",
                                           class: "btn btn-large btn-danger pull-right" %>
            <% end %>
            <%= f.submit "Обновить", class: "btn btn-large btn-primary" %>
            <%= f.submit "Отмена", name: 'cancel_button', class: "btn btn-large" %>
          <% end %>
      <% end %>
    </div>
  </div> 
</section> 

app/views/forums/edit.html.erb
<% provide(:title, "Редактировать форум") %>

<%= render 'forum_form'%>

app/views/forums/index.html.erb
<% provide(:title, "Форумы") %>

<h1>Форумы</h1>
<% if current_user.admin? %>
  <%= link_to "Все топики", topics_path, class: "pull-right" %>
<% end %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th width="70%" colspan="2">Форум</th>  
      <th width="30%">Последнее сообщение</th>
    </tr>
  </thead>
  <tbody>
  <% @forums.each do |forum| %>
    <tr>
      <td width="5%" class="forum-center">
        <% if forum.protect %>
          <%= link_to image_tag('forum_close.png', title: forum.title), forum %>
        <% else %>
          <%= link_to image_tag('forum_open.png', title: forum.title), forum %>
        <% end %>
      </td>
      <td>        
        <h4><%= link_to forum.title, forum %></h4>
        <p><small><%= forum.topics.count.to_s + ' ' + Russian::pluralize((forum.topics.count), 
                                  "топик", "топика", "топиков") %></small></p>
        <% if forum.content %>
          <p><%= forum.content[0..40] + ( forum.content.length > 40 ? '...' : '' )  %></p>
        <% end %>
      </td>
      <td class="forum-center">
        <% if forum.topics.any? %>
          <% if forum.topics.first.topic_posts.any? %>
            <%= forum.topics.first.topic_posts.last.created_at %> by 
            <%= link_to forum.topics.first.topic_posts.last.user.name, forum.topics.first.topic_posts.last.user %> 
            <br/>в <%= link_to forum.topics.first.title, forum.topics.first %>
          <% else %>
            <%= forum.topics.first.created_at %> by 
            <%= link_to forum.topics.first.user.name, forum.topics.first.user %> 
            <br/>в <%= link_to forum.topics.first.title, forum.topics.first %>
          <% end %>
        <% else %>
          Нет сообщений          
        <% end %>
      </td>
      <% if current_user.admin? %>
        <td><%= link_to "Edit", edit_forum_path(forum) %></td>  
        <td><%= link_to "Delete", forum, :confirm => 'Уверены?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>      
</table>
<% if current_user.admin? %>
  <hr>
  <%= link_to "Создать новый форум", new_forum_path, class: "btn btn-primary" %>
<% end %>

app/views/forums/new.html.erb
<% provide(:title, "Новый форум") %>

<%= render 'forum_form'%>

app/views/forums/show.html.erb
<% provide(:title, @forum.title) %>

<h1><%= @forum.title %></h1>
<% if @forum.content %>
  <p><%= @forum.content %></p>
<% end %>
<hr>
<ul class="breadcrumb">
  <li><%= link_to "Форумы", forums_path %> <span class="divider">/</span></li>
  <li class="active"><%= link_to @forum.title, @forum %></li>
</ul>
<%= will_paginate @topics %>
<table class="table table-striped table-bordered">
  <thead>  
    <tr>  
      <th width="60%" colspan="2">Топик</th>  
      <th width="10%">Ответов</th>  
      <th width="30%">Последнее сообщение</th>        
    </tr>
  </thead>
  <tbody>  
    <% @topics.each do |topic| %>  
      <tr>
        <td width="5%" class="forum-center">
          <% if topic.close %>
            <%= link_to image_tag('topic_close.png', title: topic.title), topic %>
          <% else %>
            <%= link_to image_tag('topic_open.png', title: topic.title), topic %>
          <% end %>
        </td>  
        <td><%= link_to topic.title, topic %></td>  
        <td class="forum-center"><%= topic.topic_posts.count %></td>  
        <td class="forum-center">
          <% if topic.topic_posts.any? %>
            <%= topic.topic_posts.last.created_at %> by 
            <%= link_to topic.topic_posts.last.user.name, topic.topic_posts.last.user %>
          <% else %>
            Нет сообщений
          <% end %>
        </td>
        <% if (current_user?(topic.user) && !current_user.banned) || current_user.admin? %>
          <td><%= link_to "Edit", edit_topic_path(topic) %></td>  
          <td><%= link_to "Delete", topic, :confirm => 'Уверены?', :method => :delete %></td>
        <% end %>  
      </tr>  
    <% end %>
  </tbody>  
</table>
<%= will_paginate @topics %>
<ul class="breadcrumb">
  <li><%= link_to "Форумы", forums_path %> <span class="divider">/</span></li>
  <li class="active"><%= link_to @forum.title, @forum %></li>
</ul>
<hr>
<%= link_to "Создать топик", new_topic_path(forum: @forum.id), class: "btn btn-primary" if !(@forum.protect && !current_user.admin?) %>
<% if current_user.admin? %>
  <%= link_to "Удалить форум", @forum, :confirm => 'Уверены?', :method => :delete, class: "btn btn-primary btn-danger pull-right" %>
  <%= link_to "Редактировать форум", edit_forum_path(@forum), class: "btn btn-primary" %>
<% end %>