config/routes.rb
NewAnifag::Application.routes.draw do

  root :to => 'static_pages#home'

  devise_for :users, :controllers => { :invitations => 'users/invitations',
                                       :registrations => 'users/registrations' }
  
  devise_scope :user do
    get "signin", :to => "devise/sessions#new"
    match "signout", to: "devise/sessions#destroy", via: :delete
  end

  mount RedactorRails::Engine => '/redactor_rails'

  resources :users, only: [:show, :index]
  
  resources :articles  
  
  resources :categories
  resources :tags, only: [:index, :show]
  
  resources :forums
  resources :topics
  resources :topic_posts, except: [:show, :new]
  
  match '/search', to: 'static_pages#search'
  
  match '/users/:id/ban',  to: 'users#ban', as: :user_ban
  
  get '/archive(/:year(/:month))', to: 'archives#show', as: :archive
  
  get '/:year/:month/:id', to: 'articles#redirect_to_new'

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  forum_id     :integer
#  title        :string(255)
#  content      :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  last_post_at :datetime
#  close        :boolean          default(FALSE)
#

class Topic < ActiveRecord::Base
  attr_accessible :content, :title, :forum_id, :last_post_at, :close
  
  belongs_to :forum
  belongs_to :user
  
  has_many :topic_posts, dependent: :destroy
  
  validates :user_id, presence: true
  validates :forum_id, presence: true
  validates :title, presence: true, length: { maximum: 90 }
  validates :content, presence: true
  
  default_scope order: 'topics.last_post_at DESC'
end

app/controllers/topics_controller.rb
# coding: utf-8
class TopicsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user, except: [:show]
  before_filter :admin_user, only: [:index]
  
  def index    
    @topics = Topic.paginate(page: params[:page], :per_page => 30)
  end

  def create
    forum = Forum.find(params[:forum])
    if forum.protect && !current_user.admin?
      flash[:error] = "Создание топиков запрещено."
      redirect_to forum
    end
    if forum.title == 'Новости и объявления'
      title = Time.now.strftime("%Y-%m-%d") + ' - ' + params[:topic]["title"]
    else
      title = params[:topic]["title"]
    end    
    @topic = current_user.topics.build(title: title, 
                                       content: params[:topic]["content"], 
                                       forum_id: params[:forum].to_i,
                                       last_post_at: Time.now)    
    if params[:preview_button] || !@topic.save
      render 'new'
    else
      if @topic.save
        flash[:success] = "Топик создан."
        redirect_to @topic
      else
        render 'new'
      end
    end
  end

  def new
    forum = Forum.find(params[:forum])
    if forum.protect && !current_user.admin?
      flash[:error] = "Создание топиков запрещено."
      redirect_to forum
    end
    @topic = Topic.new    
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def show
    @topic = Topic.find(params[:id])
    @topic_post = current_user.topic_posts.build if user_signed_in? && !@topic.close
    query =  @topic.topic_posts
    if params[:page]
      @topic_posts = query.paginate(page: params[:page], :per_page => 20)
    else
      last_page = query.paginate(page: params[:page], :per_page => 20).total_pages
      @topic_posts = query.paginate(page: last_page, :per_page => 20)
    end   
  end

  def update
    @topic = Topic.find(params[:id])
    if params[:preview_button]
      render 'edit'
    elsif params[:cancel_button]
      redirect_to @topic
    else    
      if @topic.update_attributes(params[:topic])
        flash[:success] = "Топик обновлен."
        redirect_to @topic
      else
        render 'edit'
      end
    end
  end

  def destroy
    @topic.destroy
    flash[:success] = "Топик удален."
    redirect_to forums_url
  end
  
  private
    def correct_user
      if params[:id]
        @topic = Topic.find(params[:id])
      else 
        @topic = current_user.topics.build()
      end      
      user = @topic.user
      redirect_to forums_path unless ((current_user?(user) && !current_user.banned) || current_user.admin?)
    end
    
    def admin_user
      redirect_to forums_path unless current_user.admin?
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic_form.html.erb
<section>
  <% if controller.action_name == 'new' %> 
    <h1>Новый топик</h1>
  <% else %>
    <h1>Редактирование топика</h1>
  <% end %>
  <hr>
  <% if params[:preview_button] %>
    <h2>Предпросмотр</h2>
    <table class="table table-bordered">
      <thead>  
        <tr>  
          <th width="20%">Автор</th>  
          <th width="80%">Сообщение</th>        
        </tr>
      </thead>
      <tbody> 
        <tr>
          <td class="post-author">
            <p><strong><%= link_to @topic.user.name, user_url(@topic.user) %></strong></p>
            <%= gravatar_for @topic.user, options = { size: 120 } %>
            <% if user_role(@topic.user) %>
              <p><strong><%= user_role(@topic.user) %></strong></p>
            <% end %>
          </td>  
          <td>                    
            <%= show_content(@topic.content).html_safe %>
            <% if @topic.user.user_description.sign %>
              <p class="post-footer">
                <small><%= @topic.user.user_description.sign %></small>
              </p>
            <% end %>
          </td> 
        </tr>
      </tbody>  
    </table>
    <hr>
  <% end %>
  <div class="row">
    <div class="span12">
      <%= form_for(@topic) do |f| %>
        <% if @topic.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-error">
              Форма содержит <%= (@topic.errors.count).to_s + 
                                  " " + Russian::pluralize((@topic.errors.count), 
                                  "ошибку", "ошибки", "ошибок") %>.
            </div>
            <ul>
            <% @topic.errors.full_messages.each do |msg| %>
              <li>* <%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
  
        <%= f.label :title, "Название" %>
        <%= f.text_field :title %>
  
        <%= f.label :content, "Сообщение" %>
        <%= f.text_area :content, class: "redactor_topic" %>
        
        <hr>
        <%= f.label :close, class: "checkbox" do %>
          <%= f.check_box :close  %> Запретить комментирование
        <% end %>
        
        <%= hidden_field_tag "forum", params[:forum] %>
        
        <div class="form-actions control">         
        
          <% if controller.action_name == 'new' %>
            <%= f.submit "Создать", class: "btn btn-large btn-primary" %>
          <% else %>
            <% if @topic && @topic.id  %>
              <%= link_to "Удалить", @topic, method: :delete,
                                           data: { confirm: "Уверены?" },
                                           title: "Удалить",
                                           class: "btn btn-large btn-danger pull-right" %>
            <% end %>
            <%= f.submit "Обновить", class: "btn btn-large btn-primary" %>
            <%= f.submit "Отмена", name: 'cancel_button', class: "btn btn-large" %>
          <% end %>
          <%= f.submit 'Предпросмотр', name: 'preview_button', class: "btn btn-large" %>
        </div>
      <% end %>
    </div>
  </div> 
</section> 

app/views/topics/edit.html.erb
<% provide(:title, "Редактирование - " + @topic.title) %>
<%= render 'topic_form'%>

app/views/topics/index.html.erb
<% provide(:title, "Все топики") %>

<h1>Все топики</h1>

<%= will_paginate @topics %>

<table class="table table-striped table-bordered">
  <thead>  
    <tr>  
      <th width="30%" colspan="2">Топик</th>
      <th width="30%">Из форума</th>  
      <th width="10%">Ответов</th>  
      <th width="30%">Последний пост</th>        
    </tr>
  </thead>
  <tbody>  
    <% @topics.each do |topic| %>  
      <tr>
        <td width="5%" class="forum-img"><%= link_to image_tag('topic_open.png', title: topic.title), topic %></td>  
        <td><%= link_to topic.title, topic %></td>
        <td><%= link_to topic.forum.title, topic.forum %></td>  
        <td class="forum-center"><%= topic.topic_posts.count %></td>  
        <td class="forum-center">
          <% if topic.topic_posts.any? %>
            <%= topic.topic_posts.last.created_at %> by 
            <%= link_to topic.topic_posts.last.user.name, topic.topic_posts.last.user %>
          <% else %>
            Нет сообщений
          <% end %>
        </td>
        <% if (current_user?(topic.user) && !current_user.banned) || current_user.admin? %>
          <td><%= link_to "Edit", edit_topic_path(topic) %></td>  
          <td><%= link_to "Delete", topic, :confirm => 'Уверены?', :method => :delete %></td>
        <% end %>  
      </tr>  
    <% end %>
  </tbody>  
</table>

<%= will_paginate @topics %>

app/views/topics/new.html.erb
<% provide(:title, "Новый топик") %>
<%= render 'topic_form'%>

app/views/topics/show.html.erb
<% provide(:title, @topic.title) %>
<h1><%= @topic.title %></h1>
<hr>
<ul class="breadcrumb">
  <li><%= link_to "Форумы", forums_path %> <span class="divider">/</span></li>
  <li><%= link_to @topic.forum.title, forum_path(@topic.forum) %> <span class="divider">/</span></li>
  <li class="active"><%= link_to @topic.title, @topic %></li>
</ul>
<% if controller.action_name == 'show' %>
  <%= will_paginate @topic_posts %>
<% end %>
<table class="table table-striped table-bordered">
  <thead>  
    <tr>  
      <th width="20%">Автор</th>  
      <th width="80%">Сообщение</th>        
    </tr>
  </thead>
  <tbody> 
    <tr>
      <td class="post-author">
        <p><strong><%= link_to @topic.user.name, user_url(@topic.user) %></strong></p>
        <%= gravatar_for @topic.user, options = { size: 120 } %>
        <% if user_role(@topic.user) %>
          <p><strong><%= user_role(@topic.user) %></strong></p>
        <% end %>
      </td>  
      <td>
        <p class="post-head">
          <% if (current_user?(@topic.user) && !current_user.banned) || current_user.admin? %>
            <small class="pull-right">
              <%= link_to "Edit", edit_topic_path(@topic) %> |  
              <%= link_to "Delete", @topic, :confirm => 'Уверены?', :method => :delete %>
            </small>
          <% end %>
          <small>
            <%= @topic.created_at %>
            <% if @topic.created_at != @topic.updated_at %>
              (ред. <%= @topic.updated_at %>)
            <% end %>
          </small>
        </p>        
        <%= show_content(@topic.content).html_safe %>
        <% if @topic.user.user_description.sign %>
          <p class="post-footer">
            <small><%= @topic.user.user_description.sign %></small>
          </p>
        <% end %>
      </td> 
    </tr>
    <% if @topic.topic_posts.any? %>
      <% @topic_posts.each do |post| %>
        <tr>
          <td class="post-author">
            <p><strong><%= link_to post.user.name, user_url(post.user) %></strong></p>
            <%= gravatar_for post.user, options = { size: 120 } %>
            <% if user_role(post.user) %>
              <p><strong><%= user_role(post.user) %></strong></p>
            <% end %>
          </td>  
          <td>
            <p class="post-head">
              <% if (current_user?(post.user) && !current_user.banned) || current_user.admin? %>
                <small class="pull-right">
                  <%= link_to "Edit", edit_topic_post_path(post) %> |  
                  <%= link_to "Delete", post, :confirm => 'Уверены?', :method => :delete %>
                </small>
              <% end %>
              <small>
                <%= post.created_at %>
                <% if post.created_at != post.updated_at %>
                  (ред. <%= post.updated_at %>)
                <% end %>
              </small>
            </p>        
            <%= show_content(post.content).html_safe %>
            <% if post.user.user_description.sign %>
              <p class="post-footer">
                <small><%= post.user.user_description.sign %></small>
              </p>
            <% end %>
          </td> 
        </tr>
      <% end %>
    <% end %>
  </tbody>  
</table>

<% if controller.action_name == 'show' %>
  <%= will_paginate @topic_posts %>
<% end %>

<ul class="breadcrumb">
  <li><%= link_to "Форумы", forums_path %> <span class="divider">/</span></li>
  <li><%= link_to @topic.forum.title, forum_path(@topic.forum) %> <span class="divider">/</span></li>
  <li class="active"><%= link_to @topic.title, @topic %></li>
</ul>

<% if @topic.close %>
  <h2>Комментирование запрещено</h2>
<% else %>
  <%= render 'shared/topic_post_form' %>
<% end %>