config/routes.rb
NewAnifag::Application.routes.draw do

  root :to => 'static_pages#home'

  devise_for :users, :controllers => { :invitations => 'users/invitations',
                                       :registrations => 'users/registrations' }
  
  devise_scope :user do
    get "signin", :to => "devise/sessions#new"
    match "signout", to: "devise/sessions#destroy", via: :delete
  end

  mount RedactorRails::Engine => '/redactor_rails'

  resources :users, only: [:show, :index]
  
  resources :articles  
  
  resources :categories
  resources :tags, only: [:index, :show]
  
  resources :forums
  resources :topics
  resources :topic_posts, except: [:show, :new]
  
  match '/search', to: 'static_pages#search'
  
  match '/users/:id/ban',  to: 'users#ban', as: :user_ban
  
  get '/archive(/:year(/:month))', to: 'archives#show', as: :archive
  
  get '/:year/:month/:id', to: 'articles#redirect_to_new'

end

app/views/shared/_aside.html.erb
<% #tag_cloud(10) %>
<aside class="span3">
  <p>
    <a href="https://plus.google.com/107660702014207926001/?prsrc=3" style="text-decoration: none;">
      <img src="https://ssl.gstatic.com/images/icons/gplus-64.png" width="50" height="50" style="border: 0;" />
      </a>
    <a href="http://ru-ru.facebook.com/people/Navi-Arimeka/100002067279966" target="_TOP" title="Navi Arimeka">
      <img alt="Facebook" src="http://1.bp.blogspot.com/-EVqhKy2cnfk/TVt7DpTsX4I/AAAAAAAAAMY/QMs7ucJWMqM/s1600/facebookicon.png" width="50" height="50" style="border: 0px;" />
      </a>
    <a href="http://vk.com/anifag" target="_TOP">
      <img alt="ВКонтакте" src="https://lh5.googleusercontent.com/-Z10Dc4e7nB8/TsdXlY8AYLI/AAAAAAAAHYk/HT1mhP-JLrw/vkontakte.png" width="50" height="50" style="border: 0px;" />
      </a>
    <a href="https://twitter.com/wrk_navi" target="_TOP">
      <img alt="Twitter" src="https://lh3.googleusercontent.com/-04YLrpSai7U/TsdYRT2K3kI/AAAAAAAAHYs/fsh77MgYTAg/twitter.png" width="50" height="50" style="border: 0px;" />
    </a>
  </p>
  <hr>
  <% if @tags && @tags.any? %>
    <h4>Облако тегов</h4>
    <p><%= render 'shared/tag_cloud'%></p>
    <p><%= link_to "Все теги", tags_path %></p>
    <hr>
  <% end %>
  <%= adv_aside.html_safe %>
  <hr>
	<h4>Архив</h4>
	<dl>
		<% 0.upto(3) do |i| %>
			<% archive_list(Time.now.year - i) %>
			<% if @archive_year_count != 0 %>
				<dt>
					<%= link_to (Time.now.year - i), archive_path(Time.now.year - i) %> (<%= @archive_year_count %>)
				</dt>		
				<% x = 1 %>
				<% @archive_month_count.each do |count| %>
					<% if count != 0 %>
						<dd>
							<%= link_to Russian::strftime(Time.new((Time.now.year - i),x), "%B"), archive_path((Time.now.year - i),Time.new((Time.now.year - i),x).month) %> (<%= count %>)					
						</dd>
					<% end %>
					<% x += 1 %>
				<% end %>
			<% end %>
		<% end %>		
	</dl>
	<hr>
</aside>

app/views/shared/_edit_article.html.erb
<div class="span12">	
	<% if params[:preview_button] %>
  	<div id="preview" class="alert alert-info">  		
  		<button type="button" class="close" data-dismiss="alert">×</button>
  		<h2>Предпросмотр</h2>
  		<article class="article">
	  		<h3 class="title"><%= @article.title %></h3>
	  		<hr>
	  		<div class="body"><%= show_content(@article.content).html_safe %></div>
	  		<% unless @article.source.blank? %>
	  			<hr>
	  			<small class="source"><%= link_to "Источник", @article.source, target:"_blank" %></small>
	  		<% end %>
  		</article>
  	</div>
	<% end %>
	<% if controller.action_name == "new" || controller.action_name == "create" %>
		<% uri = '/articles' %>
		<% method = 'post' %>
	<% else %>
		<% uri = @article %>
		<% method = 'put' %>
	<% end %>
	<%= form_tag(uri, method: method) do -%>
<% if @article %>
<% if @article.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Форма содержит <%= @article.errors.count.to_s + " " + Russian::pluralize(@article.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>	
<% end %>	
		<%= label_tag 'title', 'Заголовок' %>
		<%= text_field_tag 'title', params[:title] %>
		<%= text_area_tag 'content', params[:content], class: "redactor_article" %>
		<%= label_tag 'source', 'Источник'  %>
		<%= url_field_tag 'source', params[:source], placeholder: 'http://www.example.com/' %>
		<div class="form-actions control">
			<% if controller.action_name == "new" || controller.action_name == "create" || @article.draft %>	
				<%= submit_tag "Опубликовать", class: "btn btn-large btn-primary" %>
				<%= submit_tag 'Сохранить', name: 'draft_button', class: "btn btn-large" %>
			<% else %>
				<%= submit_tag "Обновить", class: "btn btn-large btn-primary" %>
				<%= submit_tag 'В черновики', name: 'draft_button', class: "btn btn-large" %>				
			<% end %>
			<% if @article && @article.id  %>
				<%= link_to "Удалить", @article, method: :delete,
                                     data: { confirm: "Уверены?" },
                                     title: "Удалить",
                                     class: "btn btn-large btn-danger pull-right" %>
			<% end %>
			<%= submit_tag 'Предпросмотр', name: 'preview_button', class: "btn btn-large" %>
		</div>
		<section>
			<h2>Дополнительные параметры</h2>
			<hr>
			<div class="span6 meta-options">
				<h3>Поисковая оптимизация</h3>
				<hr>
				<%= label_tag 'permalink', 'Slug' %>
				<%= text_field_tag 'permalink', params[:permalink], placeholder: 'example-title-name' %>
				<%= label_tag 'keywords', 'Теги для поисковика' %>
				<%= text_field_tag 'keywords', params[:keywords], placeholder: 'tag 1,tag2,tag3' %>
				<%= label_tag 'meta-description', 'Описание для поисковика' %>
				<%= text_area_tag 'meta-description', params["meta-description"] %>
			</div>
			<div class="span5 options pull-right">
				<h3>Категории и теги</h3>
				<hr>
				<%= label_tag 'categories', 'Категории (через shift или ctrl)' %>
				<%= select_tag 'categories', options_from_collection_for_select(Category.all, "name", "title"),
				multiple: true %>
				<% if @article && !@article.categories.empty? %>Текущие категории:
					<% @article.categories.each do |x| %> 
						<%= x.title %>
					<% end %><p></p>
				<% end %>
				<%= label_tag 'tags', 'Теги' %>
				<%= text_field_tag 'tags', params[:tags] %>
			</div>
		</section>
	<% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? || (@user.user_description && @user.user_description.errors.any?) %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Форма содержит <%= (@user.errors.count + @user.user_description.errors.count).to_s + 
      										" " + Russian::pluralize((@user.errors.count + @user.user_description.errors.count), 
      										"ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    <% @user.user_description.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
	  <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_tag_cloud.html.erb
<div id="tag_cloud">
	<% @tags.order('name').each do |x| %>	  
		<%= link_to x.name, tag_path(x.name), style: "font-size:#{@tag_cloud_hash[x.id]}px;", class: "cloud_element" %>
	<% end %>
</div>

app/views/shared/_topic_post_form.html.erb
<section>
  <h2>Ответить</h2>
  <hr>
  <% if params[:preview_button] %>
    <h2>Предпросмотр</h2>
    <table class="table table-bordered">
      <thead>  
        <tr>  
          <th width="20%">Автор</th>  
          <th width="80%">Сообщение</th>        
        </tr>
      </thead>
      <tbody> 
        <tr>
          <td class="post-author">
            <p><strong><%= link_to @topic_post.user.name, user_url(@topic_post.user) %></strong></p>
            <%= gravatar_for @topic_post.user, options = { size: 120 } %>
            <% if user_role(@topic_post.user) %>
              <p><strong><%= user_role(@topic_post.user) %></strong></p>
            <% end %>
          </td>  
          <td>                    
            <%= show_content(@topic_post.content).html_safe %>
            <% if @topic_post.user.user_description.sign %>
              <p class="post-footer">
                <small><%= @topic_post.user.user_description.sign %></small>
              </p>
            <% end %>
          </td> 
        </tr>
      </tbody>  
    </table>
    <hr>
  <% end %>
  <div class="row">
    <div class="span12">
      <%= form_for(@topic_post) do |f| %>
        <% if @topic_post.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-error">
              Форма содержит <%= (@topic_post.errors.count).to_s + 
                                  " " + Russian::pluralize((@topic_post.errors.count), 
                                  "ошибку", "ошибки", "ошибок") %>.
            </div>
            <ul>
            <% @topic_post.errors.full_messages.each do |msg| %>
              <li>* <%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
  
        <%= f.text_area :content, class: "redactor_topic" %>
        
        <%= hidden_field_tag "topic", params[:id] ? params[:id] : @topic.id %>
        
        <div class="form-actions control">
          <% if controller.action_name != 'edit' %>
            <%= f.submit "Ответить", class: "btn btn-large btn-primary" %>
          <% else %>
            <% if @topic_post && @topic_post.id  %>
              <%= link_to "Удалить", @topic_post, method: :delete,
                                           data: { confirm: "Уверены?" },
                                           title: "Удалить",
                                           class: "btn btn-large btn-danger pull-right" %>
            <% end %>
            <%= f.submit "Обновить", class: "btn btn-large btn-primary" %>
            <%= f.submit "Отмена", name: 'cancel_button', class: "btn btn-large" %>
          <% end %>
          <%= f.submit 'Предпросмотр', name: 'preview_button', class: "btn btn-large" %>
        </div>
      <% end %>
    </div>
  </div> 
</section> 