config/routes.rb
NewAnifag::Application.routes.draw do

  root :to => 'static_pages#home'

  devise_for :users, :controllers => { :invitations => 'users/invitations',
                                       :registrations => 'users/registrations' }
  
  devise_scope :user do
    get "signin", :to => "devise/sessions#new"
    match "signout", to: "devise/sessions#destroy", via: :delete
  end

  mount RedactorRails::Engine => '/redactor_rails'

  resources :users, only: [:show, :index]
  
  resources :articles  
  
  resources :categories
  resources :tags, only: [:index, :show]
  
  resources :forums
  resources :topics
  resources :topic_posts, except: [:show, :new]
  
  match '/search', to: 'static_pages#search'
  
  match '/users/:id/ban',  to: 'users#ban', as: :user_ban
  
  get '/archive(/:year(/:month))', to: 'archives#show', as: :archive
  
  get '/:year/:month/:id', to: 'articles#redirect_to_new'

end

app/views/layouts/_footer.html.erb
<% cache do %>
<footer class="footer">
	<%= debug(params) if Rails.env.development? %>
  <small class="pull-right" >
    <%= link_to "RSS", 'http://feeds.feedburner.com/AnimeFag' %>
  </small>
	<small>
    <%= link_to "Anime Fag", root_path %> 
    <%= Time.now.year %>
  </small>
</footer>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "⑨ Anime Fag", root_path, :class => "brand" %>
      <ul class="nav">      	
  			<li><%= link_to "Главная", root_path %></li>
        <li><%= link_to "Vocaloid Top100", 'http://vocaloid.anifag.com/', target: '_blank' %></li>
  			<% if user_signed_in? %>
  			 <li><%= link_to "Форумы", forums_path %></li>
  			<% end %>               
		  </ul>		  		  
		  	<ul class="nav pull-right">
		  		<% if user_signed_in? %>	  		  		  		
		  			<li>		  			  
		  				<%= link_to image_tag('pencil.png', alt: "Написать пост", title: "Написать пост"), new_article_path %>
		  			</li>
		  			<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Профиль", current_user %></li>
                <% if current_user.admin?%>
                	<li>
                		<%= link_to "Отправить инвайт", new_user_invitation_path %>
                	</li>
                	<li><%= link_to "Пользователи", users_path %></li>
                	<li><%= link_to "Категории", categories_path %></li>
                	<li><%= link_to "Все топики форумов", topics_path %></li>
                	<li><%= link_to "Все сообщения форумов", topic_posts_path %></li>
                <% end %>                
                <li class="divider"></li>
                <li>
                  <%= link_to "Выйти", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
		  		<% else %>      	
  					<li><%= link_to "Войти", signin_path %></li>
  				<% end %>	            
		  	</ul>
		  <%= form_tag search_path, class: "navbar-search pull-right" do -%>
  			<%= text_field_tag 'search', '', class: "search-query", placeholder: "Поиск" %>
			<% end %>		
    </div>
  </div>
</header>

app/views/layouts/_seo.html.erb
<meta name="description" content="<%=
 @article && @article.meta_description && !@article.meta_description.empty? ? @article.meta_description : "Новости аниме и манги."
%>">
<meta name="keywords" content="новости, аниме, манга, anime fag<%=
  ", " + @article.keywords if @article && @article.keywords && !@article.keywords.empty?
%>"> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_vkontakte.html.erb
<script type="text/javascript" src="http://userapi.com/js/api/openapi.js?52"></script>

<script type="text/javascript">
  VK.init({apiId: 2686339, onlyWidgets: true});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= render 'layouts/seo' %>
  <%= render 'layouts/vkontakte' if controller.controller_name == 'articles' && controller.action_name == 'show' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
	  	<div class="alert alert-<%= key %>"><%= value %></div>
	  <% end %>
	  <div class="row-fluid">	  	
			<%= yield %>			
		</div>
		
		<%= render 'layouts/footer' %>
		<a href="#" class="scrollup">Вверх</a>
	</div>
  <% if (controller.action_name == 'home' && controller.controller_name == 'static_pages') ||
        (controller.action_name == 'show' && controller.controller_name == 'users') ||
        (controller.action_name == 'show' && controller.controller_name == 'categories')  %>	
	 <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'anifag'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function () {
            var s = document.createElement('script'); s.async = true;
            s.type = 'text/javascript';
            s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
            (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
        }());
        </script>
   <% end %>
</body>
</html>